#(Made by:"RandysGitHuubs" on GitHub )


import turtle

scr = turtle.Screen()
scr.bgcolor("black")

turtle.color("blue")
turtle.showturtle()
turtle.shape("circle")
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.end_fill()

turtle.showturtle()
turtle.shape("circle")
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.end_fill()

turtle.showturtle()
turtle.shape("circle")
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.forward(75)
turtle.right(-30)
turtle.end_fill()

turtle.done()

